name: Vulnerability scan
on: [push, pull_request]
jobs:
  vulnerabilities-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: debricked/actions/scan@main  # Change the version if needed
        env:
          DEBRICKED_TOKEN: ${{ secrets.DEBRICKED_TOKEN }}
