name: Vulnerability scan
on: [push, pull_request]
jobs:
  vulnerabilities-scan:
    runs-on: ubuntu-latest
    steps:
      # Step to check out your repository
      - uses: actions/checkout@v2
      
      # Using the correct version of Debricked's action (v1)
      - uses: debricked/actions/scan@v1
        env:
          DEBRICKED_TOKEN: ${{ secrets.DEBRICKED_TOKEN }}
